package com.xiaominote.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val md_light_primary = Color(0xFF1B6B57)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFA6F2D9)
val md_light_onPrimaryContainer = Color(0xFF002018)
val md_light_secondary = Color(0xFF4B6359)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFCDE8DB)
val md_light_onSecondaryContainer = Color(0xFF072018)
val md_light_tertiary = Color(0xFF3E6374)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFC2E8FB)
val md_light_onTertiaryContainer = Color(0xFF001F2A)
val md_light_background = Color(0xFFFBFDFA)
val md_light_onBackground = Color(0xFF191C1A)
val md_light_surface = Color(0xFFFBFDFA)
val md_light_onSurface = Color(0xFF191C1A)
val md_light_surfaceVariant = Color(0xFFDBE5DF)
val md_light_onSurfaceVariant = Color(0xFF3F4945)
val md_light_outline = Color(0xFF6F7975)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)

// Dark palette
val md_dark_primary = Color(0xFF8AD6BE)
val md_dark_onPrimary = Color(0xFF00382B)
val md_dark_primaryContainer = Color(0xFF00513F)
val md_dark_onPrimaryContainer = Color(0xFFA6F2D9)
val md_dark_secondary = Color(0xFFB1CCBF)
val md_dark_onSecondary = Color(0xFF1C352C)
val md_dark_secondaryContainer = Color(0xFF334B42)
val md_dark_onSecondaryContainer = Color(0xFFCDE8DB)
val md_dark_tertiary = Color(0xFFA6CCDF)
val md_dark_onTertiary = Color(0xFF073544)
val md_dark_tertiaryContainer = Color(0xFF254B5B)
val md_dark_onTertiaryContainer = Color(0xFFC2E8FB)
val md_dark_background = Color(0xFF191C1A)
val md_dark_onBackground = Color(0xFFE1E3E0)
val md_dark_surface = Color(0xFF191C1A)
val md_dark_onSurface = Color(0xFFE1E3E0)
val md_dark_surfaceVariant = Color(0xFF3F4945)
val md_dark_onSurfaceVariant = Color(0xFFBFC9C3)
val md_dark_outline = Color(0xFF899390)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)

// Canvas paper colors
val PaperWhite = Color(0xFFFFFFFF)
val PaperCream = Color(0xFFFFFBF0)
val PaperDark = Color(0xFF1E1E1E)
